// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgrZZp4KRLTEnmQO9IdKYiuqRTKaaEau0',
    appId: '1:1015861605608:android:1cdc162ea8f250c7ab855d',
    messagingSenderId: '1015861605608',
    projectId: 'jebnah-d70fd',
    storageBucket: 'jebnah-d70fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjbDHXM_s5aBV8UtV4bSOzWHs9HjVw_MU',
    appId: '1:1015861605608:ios:165439a56a259585ab855d',
    messagingSenderId: '1015861605608',
    projectId: 'jebnah-d70fd',
    storageBucket: 'jebnah-d70fd.firebasestorage.app',
    iosBundleId: 'com.canarywebs.jebnah',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDmxgOAjPs4xSEEgaVIDCd_FXCQyFWg-s',
    appId: '1:1090280767907:web:8703626713a04f7b139a16',
    messagingSenderId: '1015861605608',
    projectId: 'jebnah-d70fd',
    authDomain: 'jebnah-d70fd.firebaseapp.com',
    storageBucket: 'jebnah-d70fd.firebasestorage.app',
  );
}
